/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import ConexaoBD.DAOUsuario;
import Email.EnviarEmail;
import Objetos.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Matheus
 */
public class Tela_Inicial_Login extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Inicial_Login
     */
    public Tela_Inicial_Login() {
        initComponents();
        pRecuperarSenha.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pRecuperarSenha = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tRecuperarSenha = new javax.swing.JTextField();
        bRecuperarSenha = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextFieldUsuario1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        bEntrar = new javax.swing.JButton();
        bCadastrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pRecuperarSenha.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Digite o seu email para recuperar a senha.");

        tRecuperarSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        bRecuperarSenha.setText("Recuperar senha");
        bRecuperarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRecuperarSenhaActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pRecuperarSenhaLayout = new javax.swing.GroupLayout(pRecuperarSenha);
        pRecuperarSenha.setLayout(pRecuperarSenhaLayout);
        pRecuperarSenhaLayout.setHorizontalGroup(
            pRecuperarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRecuperarSenhaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pRecuperarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tRecuperarSenha)
                    .addGroup(pRecuperarSenhaLayout.createSequentialGroup()
                        .addGroup(pRecuperarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(pRecuperarSenhaLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(bRecuperarSenha))
                            .addComponent(jButton1))
                        .addGap(0, 46, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pRecuperarSenhaLayout.setVerticalGroup(
            pRecuperarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRecuperarSenhaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tRecuperarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bRecuperarSenha)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        getContentPane().add(pRecuperarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 240));

        jTextFieldUsuario1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldUsuario1.setToolTipText("Email ou CPF");
        jTextFieldUsuario1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(jTextFieldUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 300, 38));
        jTextFieldUsuario1.getAccessibleContext().setAccessibleName("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Email ou CPF:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Senha:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 300, 38));

        bEntrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bEntrar.setText("Entrar");
        bEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(bEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 90, -1));

        bCadastrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bCadastrar.setText("Cadastrar");
        bCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(bCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        jLabel3.setText("Esqueci a minha senha");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void bEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEntrarActionPerformed
        String emailCPF=jTextFieldUsuario1.getText(), senha=jPasswordField1.getText();
        Usuario verificador=null;
        if(emailCPF.contains("@")){
            verificador = new Usuario("","","",emailCPF,senha,0);
        }
        else{
            verificador = new Usuario("","",emailCPF,"",senha,0);
        }
        //System.out.println("Email: "+verificador.getEmail()+"\nCPF: "+verificador.getCpf());
        DAOUsuario servicos= new DAOUsuario();
        Usuario usuarioNoBD=servicos.verificarUsuariosCadastrados(verificador);
        
        if(usuarioNoBD==null){
            JOptionPane.showMessageDialog(null, "Usuário não cadastrado", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else{
            if(senha.equals(usuarioNoBD.getSenha())){
                Tela_opcoes a= new Tela_opcoes(usuarioNoBD);
                a.setVisible(true);
                this.setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(null, "Email/CPF ou senha incorretos", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_bEntrarActionPerformed

    private void bCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadastrarActionPerformed
        Usuario nulo = null;
        Tela_CadastroModificar_Usuario abrir= new Tela_CadastroModificar_Usuario(true, nulo);
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bCadastrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        pRecuperarSenha.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void bRecuperarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRecuperarSenhaActionPerformed
        String email = tRecuperarSenha.getText();
        DAOUsuario servicos= new DAOUsuario();
        Usuario usuario = new Usuario("","","",email,"",0);
        Usuario usuarioNoBD=servicos.verificarUsuariosCadastrados(usuario);
        if(usuarioNoBD.getEmail().equals(email)){
            EnviarEmail enviar = new EnviarEmail();
            enviar.enviarSenha(usuarioNoBD);
        }
        else{
            JOptionPane.showMessageDialog(null, "O email está incorreto ou não existe!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        pRecuperarSenha.setVisible(false);
        JOptionPane.showMessageDialog(null, "Verifique o seu email!\nUma mensagem foi enviada para você!");
    }//GEN-LAST:event_bRecuperarSenhaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pRecuperarSenha.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicial_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicial_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicial_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicial_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Inicial_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCadastrar;
    private javax.swing.JButton bEntrar;
    private javax.swing.JButton bRecuperarSenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextFieldUsuario1;
    private javax.swing.JPanel pRecuperarSenha;
    private javax.swing.JTextField tRecuperarSenha;
    // End of variables declaration//GEN-END:variables
}
