/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import ConexaoBD.DAOUsuario;
import Email.EnviarEmail;
import Objetos.Usuario;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Matheus
 */
public class Tela_CadastroModificar_Usuario extends javax.swing.JFrame {
    boolean cadastrandoUsuario;
    Usuario u, usuarioNovo =null;
    DAOUsuario usuarioBD = new DAOUsuario ();
    int codigo, tentativas = 1;
    
    /**
     * Creates new form Tela_CAdastro_Usuario
     */
    public Tela_CadastroModificar_Usuario(boolean cadastro, Usuario usuario) {
        initComponents();
        this.cadastrandoUsuario = cadastro;
        u=usuario;
        
        tCPF.setEditable(cadastro);        
        bDeletar.setVisible(false);
        if(cadastro == false ){
            bCadastrarAtualizar.setText("Atualizar");
            tCPF.setEditable(false);
            bDeletar.setVisible(true);
        }
        
        jPanel1.setVisible(false);
        lblCodigoInvalido.setVisible(false);
    }

    private Tela_CadastroModificar_Usuario() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tVerificar = new javax.swing.JTextField();
        bVerificar = new javax.swing.JButton();
        bCancelarVerificacaoDeEmail = new javax.swing.JButton();
        lblCodigoInvalido = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tNome = new javax.swing.JTextField();
        tSobrenome = new javax.swing.JTextField();
        tEmail = new javax.swing.JTextField();
        bCadastrarAtualizar = new javax.swing.JButton();
        bVoltar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tSaldo = new javax.swing.JFormattedTextField();
        tCPF = new javax.swing.JFormattedTextField();
        bDeletar = new javax.swing.JButton();
        tpSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Informações do usuário");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Digite o código de verificação enviado para o seu e-mail: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        tVerificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tVerificar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(tVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 346, 44));

        bVerificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bVerificar.setText("Verificar");
        bVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerificarActionPerformed(evt);
            }
        });
        jPanel1.add(bVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        bCancelarVerificacaoDeEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bCancelarVerificacaoDeEmail.setText("Cancelar");
        bCancelarVerificacaoDeEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarVerificacaoDeEmailActionPerformed(evt);
            }
        });
        jPanel1.add(bCancelarVerificacaoDeEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        lblCodigoInvalido.setForeground(new java.awt.Color(255, 0, 51));
        lblCodigoInvalido.setText("Código inválido!");
        jPanel1.add(lblCodigoInvalido, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, -7, 410, 350));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 61, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Sobrenome:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 105, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("CPF: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 148, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Email:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 193, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Senha:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 238, -1, -1));

        tNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tNomeKeyTyped(evt);
            }
        });
        getContentPane().add(tNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 51, 300, 38));

        tSobrenome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tSobrenome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tSobrenomeKeyTyped(evt);
            }
        });
        getContentPane().add(tSobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 95, 300, 38));

        tEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tEmailKeyTyped(evt);
            }
        });
        getContentPane().add(tEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 183, 300, 38));

        bCadastrarAtualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bCadastrarAtualizar.setText("Cadastrar");
        bCadastrarAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadastrarAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(bCadastrarAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 316, -1, -1));

        bVoltar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bVoltar.setText("Voltar");
        bVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(bVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Saldo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 80, -1));

        tSaldo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###.0"))));
        tSaldo.setText("0,0");
        tSaldo.setToolTipText("Pode ser definido depois. Para isso deixe o campo em branco");
        getContentPane().add(tSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 272, 300, 38));

        try {
            tCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(tCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 139, 300, 38));

        bDeletar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bDeletar.setText("Deletar conta");
        bDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeletarActionPerformed(evt);
            }
        });
        getContentPane().add(bDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 316, -1, -1));
        getContentPane().add(tpSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 229, 300, 38));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarActionPerformed
        if(cadastrandoUsuario){
            Tela_Inicial_Login abrir= new Tela_Inicial_Login();
            abrir.setVisible(true);
            this.setVisible(false);
        }
        else{
            Tela_opcoes abrir = new Tela_opcoes(u);
            abrir.setVisible(true);
            this.setVisible(false);
        }
            
    }//GEN-LAST:event_bVoltarActionPerformed

    private void bCadastrarAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadastrarAtualizarActionPerformed
        if(cadastrandoUsuario){
            cadastrar();
        }
        else{
            atualizar();
        }
    }//GEN-LAST:event_bCadastrarAtualizarActionPerformed

    private void bDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeletarActionPerformed
        Object[] options = { "Cancelar", "Confirmar" };
        int opcao = JOptionPane.showOptionDialog(null, "Tem certeza que deseja deletar sua conta?", "Aviso", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
        if(opcao>0){
            usuarioBD.apagarConta(u);
            Tela_Inicial_Login abrir = new Tela_Inicial_Login();
            abrir.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_bDeletarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        if(cadastrandoUsuario == false){
            tNome.setText(u.getNome());
            tSobrenome.setText(u.getSobrenome());
            tCPF.setText(u.getCpf());
            tEmail.setText(u.getEmail());
            tpSenha.setText(u.getSenha());
            tSaldo.setText(""+u.getSaldo());
            tCPF.setEditable(false);
        }
            
    }//GEN-LAST:event_formWindowOpened

    //Caminho: cadastrar() --> bVerificarActionPerformed --> finalizarCadastro()
    public void cadastrar(){
        // Pegar dados que o usuário preencheu. Depois é verificado se o e-mail e/ou o CPF já estão cadastrados. O cadastro é realizado
        double saldo=0.0;
        if(tSaldo.getText()!=null || tSaldo.getText() !=""){
            saldo=Double.parseDouble(tSaldo.getText().replaceAll(",","."));
        }
        boolean prosseguir=true;
        usuarioNovo = new Usuario(tNome.getText(),tSobrenome.getText(),tCPF.getText(),tEmail.getText(),tpSenha.getText(),saldo);
        DAOUsuario servicos= new DAOUsuario();
        Usuario u1=servicos.verificarUsuariosCadastrados(usuarioNovo); //Verifica se já existe um usuário cadastrado com o mesmo email ou cpf     
        
        if(u1!=null){
            JOptionPane.showMessageDialog(null, "CPF ou e-mail já cadastrado", "Erro", JOptionPane.ERROR_MESSAGE);
            prosseguir=false;
        }
        else{
            //Se os dados não tiverem sido utilizados é possível criar o usuário
            //prosseguir=servicos.cadastrarUsuario(usuarioNovo);
            
            Random aleatorio = new Random();
            do{
                codigo = aleatorio.nextInt(1000000);
            }while(codigo<100000);
            EnviarEmail enviar = new EnviarEmail();
            boolean enviado = enviar.verificarEmail(usuarioNovo, codigo);
            if(enviado){
                jPanel1.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "Verifique se seu email está escrito corretamente.", "Verifique o email", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void bVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerificarActionPerformed
        boolean prosseguir =false;
        if(tentativas<=3 && prosseguir==false){
            int codigoEscrito = Integer.parseInt(tVerificar.getText());
            if(codigoEscrito == codigo){
                prosseguir = true;
            }
            else{
                tVerificar.setText("");
                lblCodigoInvalido.setVisible(true);
                tentativas++;
            }
        }
        if(prosseguir){
            finalizarCadastro();
        }
        else if(tentativas>3){
            jPanel1.setVisible(false);
            JOptionPane.showMessageDialog(null, "Código expirado");
            tentativas = 0;
        }
    }//GEN-LAST:event_bVerificarActionPerformed

    private void bCancelarVerificacaoDeEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarVerificacaoDeEmailActionPerformed
        tentativas = 1;
        jPanel1.setVisible(false);
    }//GEN-LAST:event_bCancelarVerificacaoDeEmailActionPerformed

    private void tNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNomeKeyTyped
        int limite=20;
        if(tNome.getText().length()>=limite){
          evt.consume();
        }
    }//GEN-LAST:event_tNomeKeyTyped

    private void tSobrenomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tSobrenomeKeyTyped
        int limite=20;
        if(tSobrenome.getText().length()>=limite){
          evt.consume();
        }
    }//GEN-LAST:event_tSobrenomeKeyTyped

    private void tEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tEmailKeyTyped
        int limite=254;
        if(tEmail.getText().length()>=limite){
          evt.consume();
        }
    }//GEN-LAST:event_tEmailKeyTyped
    

    public void finalizarCadastro(){
        DAOUsuario servicos = new DAOUsuario();
        boolean prosseguir=servicos.cadastrarUsuario(usuarioNovo);
        if(prosseguir){
            //Prossegue para a próxima tela com os dados já cadastrados se não houver nenhum erro anteriormente
            Tela_opcoes abrir = new Tela_opcoes(usuarioNovo);
            abrir.setVisible(true);
            this.setVisible(false); 
        }
       
    }
    
    public void atualizar(){
        String nome = tNome.getText();
        String sobrenome = tSobrenome.getText();
        String cpf = tCPF.getText();
        String email = tEmail.getText();
        String senha = tpSenha.getText();
        double saldo = Double.parseDouble(tSaldo.getText().replaceAll(",","."));

        u.setNome(nome);
        u.setSobrenome(sobrenome);
        u.setCpf(cpf);
        u.setEmail(email);
        u.setSenha(senha);
        u.setSaldoManual(saldo);
        
        usuarioBD.atualizarUsuario(u);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_CadastroModificar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_CadastroModificar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_CadastroModificar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_CadastroModificar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_CadastroModificar_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCadastrarAtualizar;
    private javax.swing.JButton bCancelarVerificacaoDeEmail;
    private javax.swing.JButton bDeletar;
    private javax.swing.JButton bVerificar;
    private javax.swing.JButton bVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCodigoInvalido;
    private javax.swing.JFormattedTextField tCPF;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tNome;
    private javax.swing.JFormattedTextField tSaldo;
    private javax.swing.JTextField tSobrenome;
    private javax.swing.JTextField tVerificar;
    private javax.swing.JPasswordField tpSenha;
    // End of variables declaration//GEN-END:variables
}
